name: Publish to Registry
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Set outputs
      id: vars
      run: cd ..;echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: phynias/docker-events-pushover
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        tags: "latest,${{ steps.vars.outputs.sha_short }}"
        #cache: true